---
name: cmpsc-101-fall-2018-practical4
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        practicalfour/CaesarCipher.java:
            --multi 4 --language Java
            --fragment "println(" --count 4 --exact
# --> check the number of commits beyond a threshold
--commits 14
# --> check that the program executes and produces lines of output
--command "gradle -q --console plain run" --executes
--command "gradle -q --console plain run" --count 4 --exact
--command "gradle -q --console plain run" --fragment "EAGLE" --count 1 --exact
--command "gradle -q --console plain run" --fragment "HDJOH" --count 1 --exact
--command "gradle -q --console plain run" --fragment "JOE'S" --count 1 --exact
